# Generated by Django 5.0.1 on 2024-01-12 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileuser",
            options={
                "verbose_name": "ProfileUser",
                "verbose_name_plural": "ProfileUsers",
            },
        ),
        migrations.RemoveField(
            model_name="profileuser",
            name="slug",
        ),
        migrations.AlterModelTable(
            name="profileuser",
            table="profiles",
        ),
    ]
