# Generated by Django 5.0.1 on 2024-01-12 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_profileuser_options_remove_profileuser_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileuser",
            options={},
        ),
        migrations.AlterModelTable(
            name="profileuser",
            table=None,
        ),
    ]
