# Generated by Django 5.0.1 on 2024-01-12 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_alter_profileuser_options_alter_profileuser_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileuser",
            old_name="username",
            new_name="forum_user_id",
        ),
    ]
