# Generated by Django 5.0.1 on 2024-01-12 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_rename_username_profileuser_forum_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileuser",
            old_name="forum_user_id",
            new_name="forum_user",
        ),
    ]
