# Generated by Django 5.0.1 on 2024-01-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_rename_forum_user_id_profileuser_forum_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileuser",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
