# Generated by Django 5.0.1 on 2024-01-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_forumuser_last_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
