# Generated by Django 5.0.3 on 2024-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_forumuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/profiles/avatars/"
            ),
        ),
    ]
