[bumpversion]
current_version = "0.0.1"
commit = true
tag = true
tag_name = "v{new_version}"
message = "Bump version: {current_version} → {new_version}"

[bumpversion_file_py_june_settings_py]
search = 'VERSION = "{current_version}"'
replace = 'VERSION = "{new_version}"'