# Generated by Django 5.0.1 on 2024-02-06 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reactions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reactions",
        ),
    ]
