# Generated by Django 5.0.3 on 2024-03-29 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-user__username"],
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AlterModelTable(
            name="subscription",
            table="subscriptions",
        ),
    ]
